CREATE DATABASE QL_HeThongThiTracNghiem
GO 
USE QL_HeThongThiTracNghiem
GO	
CREATE TABLE Khoá_Học
(
	MaKhoa VARCHAR(10) PRIMARY KEY,
	TenKhoa VARCHAR(100)
);
GO	
CREATE TABLE Lớp
(
	MaLop VARCHAR(10) PRIMARY KEY,
	TenLop VARCHAR(100),
	MaKhoa VARCHAR(10) FOREIGN KEY REFERENCES dbo.Khoá_Học(MaKhoa)
);
GO
CREATE TABLE Phân_Quyền
(
	MaPhanQuyen VARCHAR(10) PRIMARY KEY,
	TenPhanQuyen VARCHAR(100)
);
GO
CREATE TABLE Môn_Học
(
	MaMon VARCHAR(10) PRIMARY KEY,
	TenMon VARCHAR(10),
	MaKhoa VARCHAR(10) FOREIGN KEY REFERENCES dbo.Khoá_Học(MaKhoa)
); 
GO
CREATE TABLE Tài_Khoản
(
	MaTaiKhoan VARCHAR(10) PRIMARY KEY,
	TenDN VARCHAR(10),
	MatKhau VARCHAR(10),
	MaPhanQuyen VARCHAR(10) FOREIGN KEY REFERENCES dbo.Phân_Quyền(MaPhanQuyen),
	TrangThai VARCHAR(10),
	MaLop VARCHAR(10) FOREIGN KEY REFERENCES dbo.Lớp(MaLop)
);
GO
CREATE TABLE Học_Sinh
(
	MaHS VARCHAR(10) PRIMARY KEY,
	HoTen VARCHAR(100),
	NgaySinh DATE,
	GioiTinh VARCHAR(10),
	SDT VARCHAR(10),
	DiaChi VARCHAR(10),
	MaTaiKhoan VARCHAR(10) FOREIGN KEY REFERENCES dbo.Tài_Khoản(MaTaiKhoan)
); 
GO
CREATE TABLE Giáo_Viên
(
	MaGV VARCHAR(10) PRIMARY KEY,
	HoTen VARCHAR(100),
	NgaySinh DATE,
	GioiTinh VARCHAR(10),
	SDT VARCHAR(10),
	DiaChi VARCHAR(10),
	MaTaiKhoan VARCHAR(10) FOREIGN KEY REFERENCES dbo.Tài_Khoản(MaTaiKhoan)
);
GO
CREATE TABLE Loại_Đề
(
	MaLoaiDe VARCHAR(10) PRIMARY KEY,
	TenLoaiDe VARCHAR(100)
);
GO
CREATE TABLE Nhóm_Câu_Hỏi
(
	MaNhom VARCHAR(10) PRIMARY KEY,
	TenNhom VARCHAR(100),
	MaMon VARCHAR(10) FOREIGN KEY REFERENCES dbo.Môn_Học(MaMon),
	SoCauHoi INT
);
GO 
CREATE TABLE Câu_Hỏi
(
	MaCauHoi VARCHAR(10) PRIMARY KEY,
	PhanCauHoi VARCHAR(100),
	PhanCauTraLoi VARCHAR(100),
	DapAn VARCHAR(100),
	MaNhom VARCHAR(10) FOREIGN KEY REFERENCES dbo.Nhóm_Câu_Hỏi(MaNhom)
);
GO 
CREATE TABLE Đoạn_Văn
(
	MaDoanVan VARCHAR(10) PRIMARY KEY,
	TenDoanVan VARCHAR(100),
	MaNhom VARCHAR(10) FOREIGN KEY REFERENCES dbo.Nhóm_Câu_Hỏi(MaNhom),
	TrangThai VARCHAR(10)
);
GO 
CREATE TABLE Đề_Thi
(
	MaDe VARCHAR(10) PRIMARY KEY,
	TenDe VARCHAR(100),
	ThoiGianLamBai INT,
	ThoiGianBatDau DATETIME,
	ThoiGianKetThuc DATETIME,
	MaMon VARCHAR(10) FOREIGN KEY REFERENCES dbo.Môn_Học(MaMon),
	MaNhom VARCHAR(10) FOREIGN KEY REFERENCES dbo.Nhóm_Câu_Hỏi(MaNhom),
	MaGV VARCHAR(10) FOREIGN KEY REFERENCES dbo.Giáo_Viên(MaGV),
	MaLoaiDe VARCHAR(10) FOREIGN KEY REFERENCES dbo.Loại_Đề(MaLoaiDe),
	SoDeThiDuocTao INT,
	DaoDapAn BIT,
	TrangThai VARCHAR(10)
);
GO 
CREATE TABLE Bài_Làm
(
	MaBaiLam VARCHAR(10) PRIMARY KEY,
	MaHS VARCHAR(10) FOREIGN KEY REFERENCES dbo.Học_Sinh(MaHS),
	MaDe VARCHAR(10) FOREIGN KEY REFERENCES dbo.Đề_Thi(MaDe),
	Diem INT
);	
GO
CREATE TABLE Kết_Quả
(
	MaHS VARCHAR(10) FOREIGN KEY REFERENCES dbo.Học_Sinh(MaHS),
	MaMon VARCHAR(10) FOREIGN KEY REFERENCES dbo.Môn_Học(MaMon),
	MaBaiLam VARCHAR(10) FOREIGN KEY REFERENCES dbo.Bài_Làm(MaBaiLam),
	Diem INT
);