//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bài_Làm
    {
        public string MaBaiLam { get; set; }
        public string MaHS { get; set; }
        public string MaDe { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual Đề_Thi Đề_Thi { get; set; }
        public virtual Học_Sinh Học_Sinh { get; set; }
    }
}
