//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Câu_Hỏi
    {
        public string MaCauHoi { get; set; }
        public string PhanCauHoi { get; set; }
        public string PhanCauTraLoi { get; set; }
        public string DapAn { get; set; }
        public string MaNhom { get; set; }
    
        public virtual Nhóm_Câu_Hỏi Nhóm_Câu_Hỏi { get; set; }
    }
}
