//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Môn_Học
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Môn_Học()
        {
            this.Đề_Thi = new HashSet<Đề_Thi>();
            this.Nhóm_Câu_Hỏi = new HashSet<Nhóm_Câu_Hỏi>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string MaKhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đề_Thi> Đề_Thi { get; set; }
        public virtual Khoá_Học Khoá_Học { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhóm_Câu_Hỏi> Nhóm_Câu_Hỏi { get; set; }
    }
}
