//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhóm_Câu_Hỏi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhóm_Câu_Hỏi()
        {
            this.Câu_Hỏi = new HashSet<Câu_Hỏi>();
            this.Đề_Thi = new HashSet<Đề_Thi>();
            this.Đoạn_Văn = new HashSet<Đoạn_Văn>();
        }
    
        public string MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string MaMon { get; set; }
        public Nullable<int> SoCauHoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Câu_Hỏi> Câu_Hỏi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đề_Thi> Đề_Thi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đoạn_Văn> Đoạn_Văn { get; set; }
        public virtual Môn_Học Môn_Học { get; set; }
    }
}
