//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tài_Khoản
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tài_Khoản()
        {
            this.Giáo_Viên = new HashSet<Giáo_Viên>();
            this.Học_Sinh = new HashSet<Học_Sinh>();
        }
    
        public string MaTaiKhoan { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public string MaPhanQuyen { get; set; }
        public string TrangThai { get; set; }
        public string MaLop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giáo_Viên> Giáo_Viên { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Học_Sinh> Học_Sinh { get; set; }
        public virtual Lớp Lớp { get; set; }
        public virtual Phân_Quyền Phân_Quyền { get; set; }
    }
}
