//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Đoạn_Văn
    {
        public string MaDoanVan { get; set; }
        public string TenDoanVan { get; set; }
        public string MaNhom { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Nhóm_Câu_Hỏi Nhóm_Câu_Hỏi { get; set; }
    }
}
