//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTestWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Đề_Thi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Đề_Thi()
        {
            this.Bài_Làm = new HashSet<Bài_Làm>();
        }
    
        public string MaDe { get; set; }
        public string TenDe { get; set; }
        public Nullable<int> ThoiGianLamBai { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string MaMon { get; set; }
        public string MaNhom { get; set; }
        public string MaGV { get; set; }
        public string MaLoaiDe { get; set; }
        public Nullable<int> SoDeThiDuocTao { get; set; }
        public Nullable<bool> DaoDapAn { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bài_Làm> Bài_Làm { get; set; }
        public virtual Giáo_Viên Giáo_Viên { get; set; }
        public virtual Loại_Đề Loại_Đề { get; set; }
        public virtual Môn_Học Môn_Học { get; set; }
        public virtual Nhóm_Câu_Hỏi Nhóm_Câu_Hỏi { get; set; }
    }
}
